apiVersion: v1
kind: PersistentVolume
metadata:
  name: prod-db-dump
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  nfs:
    path: /export/nfs/backups
    server: nfs.example.com
