apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prod-db-dump
  namespace: backup
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: prod-db-dump
